pipeline:
  lint:
    image: golang:1.19.1
    commands:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.49.0
      - golangci-lint --version
      - golangci-lint run
